### ISSUE TITLE
Launcher gets stuck trying to change directories

### ISSUE THREAD

**Issue by windBugg** [TheNexusAvenger/Nexus-LU-Launcher#2]
If I try to change the client install location from my C drive to the D drive when there are no files in the default folder it gets stuck trying to move non-existent files to change the directory

**Comment by TheNexusAvenger** [comment]
This should have been fixed in V.0.3.4 due to an error I made thinking `Directory.MoveDirectory` would handle separate drives.
The project is no longer maintained as of today, so it most likely won't be fixed if there is another case that I didn't account for.
